spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true
    hibernate:
      ddl_auto: none
  h2:
    console.enabled: true
    console.path: /h2-console
    console.settings.trace: false

graphql:
  servlet:
    mapping: /test
graphiql:
  mapping: /graphiql
  endpoint: /test
  props:
    variables:
      headerEditorEnabled: true